[book]
authors = ["The Servo Project Developers"]
language = "en"
src = "src"
title = "The Servo Book"

[output.html]
git-repository-url = "https://github.com/servo/book"
edit-url-template = "https://github.com/servo/book/edit/main/{path}"
site-url = "/"
# Putting additional-css and additional-js in src/ gives them live reload.
additional-css = ["src/custom.css"]
additional-js = ["src/mermaid.min.js", "src/mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
